export { default as Login } from './Account/Login' ;
export { default as DashboardInitial } from './Dashboard/DashboardInitial';
export { default as CaseDetail } from './Case/CaseDetail';
export { default as AddCasePage } from './Case/CaseDetail';
export { default as AllAssets } from './Asset/AllAssets';
export { default as AssetDetailPage } from './Asset/AssetDetailPage';
export { default as CaseAssets } from './Asset/CaseAssets';
export { default as CreateCase } from './Case/CreateCase';
export { default as ForefeitedCases } from './Dashboard/ForefietedCases';
export { default as InitialCases } from './Dashboard/InitialCases';
export { default as ClosedCases } from './Dashboard/ClosedCases';
export { default as HqReport } from './Report/HqReport';